services:
  web:
    container_name: "web"
    image: nginx:1.27.3
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - app-network

  app:
    build: ./docker/php/
    depends_on:
      - mysql
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: CocoLog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge