# fly.toml app configuration file generated for cocolog on 2025-01-27T18:13:49+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cocolog'
primary_region = 'nrt'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[build]
  dockerfile = ".fly/Dockerfile.fly"

[env]
  APP_URL = "https://cocolog.fly.dev/"
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"
  DB_HOST = "cocolog-db.internal"
  DB_DATABASE= "cocolog" 
  DB_PORT = 5432